name: Add Domain

on:
  push:
    branches:
      - main
    paths:
      - 'domains/*.json'

jobs:
  update-dns:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Parse JSON and Update Cloudflare DNS
      env:
        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
      run: |
        for FILE in domains/*.json; do
          # Parse JSON fields
          DOMAIN=$(jq -r '.record.CNAME' "$FILE")
          USERNAME=$(jq -r '.owner.username' "$FILE")

          if [[ -z "$DOMAIN" || -z "$USERNAME" ]]; then
            continue
          fi

          curl -X POST "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/dns_records" \
            -H "Authorization: Bearer $CF_API_TOKEN" \
            -H "Content-Type: application/json" \
            --data '{
              "type": "CNAME",
              "name": "'"$DOMAIN"'",
              "content": "'"$USERNAME"'.github.io",
              "ttl": 3600,
              "proxied": false
            }'
        done
